<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Ma page profile</title>
    <link rel="stylesheet" href="<?php echo $this->basePath('css/user.css'); ?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="">
    <div class="navbar">
        <a href="#">Accueil</a>
        <a href="#">À propos</a>
        <a href="#">Services</a>
        <a href="#">Contact</a>
    </div>
</div>

<div class="container">
    <?php echo $this->content; ?>
</div>
<!-- Le reste du contenu de votre page ici -->

</body>
</html>
