
<?php $this->layout('layout/userLayout'); ?>

<div class="container col-6">
    <div class="d-flex align-items-center justify-content-between mt-3">
        <h2 class="text-center">Page utilisateurs</h2>
        <a class="btn btn-primary" href="<?= $this->url('user', ['action' => 'detail', 'id' => $user->id]) ?>">Ajouter un User</a>
    </div>
</div>

<?php foreach ($users as $user) : ?>
    <div class="container col-6 mt-3">
        <div class="profile">
            <div class="profile-card">
                <input type="submit" value="add">
                <div class="profile-image">
                    <img src="chemin_vers_l_image" alt="Photo de profil">
                </div>
                <div class="profile-info">
                    <h2><?= $this->escapeHtml($user->nom).' '.$this->escapeHtml($user->prenom) ?></h2>
                    <p>Spécialité : </p>
                    <a class="btn btn-primary" href="<?= $this->url('user', ['action' => 'detail', 'id' => $user->id]) ?>">Détails</a>
                </div>
            </div>
        </div>
    </div>
<?php endforeach ;?>

<style>
    .profile-card {
        background-color: #f2f2f2;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        display: flex;
        align-items: center;
    }

    .profile-image img {
        width: 80px;
        height: 80px;
        border-radius: 50%;
    }

    .profile-info {
        margin-left: 20px;
    }

    .profile-info h2 {
        font-size: 24px;
        margin: 0;
    }

    .profile-info p {
        font-size: 16px;
        color: #555;
        margin: 5px 0;
    }

</style>
