<!DOCTYPE html>
<html>
<head>
    <title>Mon application Laminas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

    <main>
        <?php echo $this->content; ?>
    </main>

    <footer>

    </footer>
</body>
</html>
